# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\33398\PycharmProjects\FQA\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(QtGui.QMainWindow):

    def __init__(self, QWidget_parent=None):
        super().__init__(QWidget_parent)
        self.setupUi()

    def setupUi(self):
        self.setObjectName(_fromUtf8("MainWindow"))
        self.resize(711, 452)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/064.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setIconSize(QtCore.QSize(40, 40))

        self.centralWidget = QtGui.QWidget(self)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))

        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 700, 400))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))

        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))

        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))

        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))

        self.gridLayoutAnalyze = QtGui.QWidget(self.tabGeneral)
        self.gridLayoutAnalyze.setGeometry(QtCore.QRect(1, 1, 650, 150))
        self.gridLayoutAnalyze.setObjectName(_fromUtf8("gridLayoutAnalyze"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutAnalyze)
        self.gridLayout.setMargin(10)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayoutAnalyze"))
        self.btnDisableWinUpdate = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnDisableWinUpdate.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Disclaimer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDisableWinUpdate.setIcon(icon1)
        self.btnDisableWinUpdate.setIconSize(QtCore.QSize(50, 50))
        self.btnDisableWinUpdate.setObjectName(_fromUtf8("btnDisableWinUpdate"))
        self.gridLayout.addWidget(self.btnDisableWinUpdate, 1, 2, 1, 1)
        self.btnShowSysInfo = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnShowSysInfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnShowSysInfo.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/System Task.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShowSysInfo.setIcon(icon2)
        self.btnShowSysInfo.setIconSize(QtCore.QSize(50, 50))
        self.btnShowSysInfo.setObjectName(_fromUtf8("btnShowSysInfo"))
        self.gridLayout.addWidget(self.btnShowSysInfo, 1, 1, 1, 1)
        self.btnClearLogs = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnClearLogs.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Urgent Property.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClearLogs.setIcon(icon3)
        self.btnClearLogs.setIconSize(QtCore.QSize(50, 50))
        self.btnClearLogs.setObjectName(_fromUtf8("btnClearLogs"))
        self.gridLayout.addWidget(self.btnClearLogs, 1, 3, 1, 1)
        self.btnScheduller = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnScheduller.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Administrative Tools.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnScheduller.setIcon(icon4)
        self.btnScheduller.setIconSize(QtCore.QSize(50, 50))
        self.btnScheduller.setObjectName(_fromUtf8("btnScheduller"))
        self.gridLayout.addWidget(self.btnScheduller, 0, 2, 1, 1)
        self.btnUAC = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnUAC.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Remove User Male.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUAC.setIcon(icon5)
        self.btnUAC.setIconSize(QtCore.QSize(50, 50))
        self.btnUAC.setObjectName(_fromUtf8("btnUAC"))
        self.gridLayout.addWidget(self.btnUAC, 0, 1, 1, 1)
        self.btnNoRestartBSOD = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnNoRestartBSOD.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Support_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNoRestartBSOD.setIcon(icon6)
        self.btnNoRestartBSOD.setIconSize(QtCore.QSize(50, 50))
        self.btnNoRestartBSOD.setObjectName(_fromUtf8("btnNoRestartBSOD"))
        self.gridLayout.addWidget(self.btnNoRestartBSOD, 1, 0, 1, 1)
        self.btnPower = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnPower.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/120.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPower.setIcon(icon7)
        self.btnPower.setIconSize(QtCore.QSize(50, 50))
        self.btnPower.setObjectName(_fromUtf8("btnPower"))
        self.gridLayout.addWidget(self.btnPower, 0, 3, 1, 1)
        self.btnDisableFirewall = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnDisableFirewall.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Firewall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDisableFirewall.setIcon(icon8)
        self.btnDisableFirewall.setIconSize(QtCore.QSize(50, 50))
        self.btnDisableFirewall.setObjectName(_fromUtf8("btnDisableFirewall"))
        self.gridLayout.addWidget(self.btnDisableFirewall, 0, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutAnalyze)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 6, 1, 1)
        self.btnWallpaper = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnWallpaper.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Virtual Machine 2.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnWallpaper.setIcon(icon9)
        self.btnWallpaper.setIconSize(QtCore.QSize(50, 50))
        self.btnWallpaper.setObjectName(_fromUtf8("btnWallpaper"))
        self.gridLayout.addWidget(self.btnWallpaper, 1, 5, 1, 1)
        self.btnTODO = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.btnTODO.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Edit Property.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTODO.setIcon(icon10)
        self.btnTODO.setIconSize(QtCore.QSize(50, 50))
        self.btnTODO.setObjectName(_fromUtf8("btnTODO"))
        self.gridLayout.addWidget(self.btnTODO, 1, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutAnalyze)
        self.pushButton.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/113.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon11)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        self.btnSetIP = QtGui.QPushButton(self.gridLayoutAnalyze)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetIP.sizePolicy().hasHeightForWidth())
        self.btnSetIP.setSizePolicy(sizePolicy)
        self.btnSetIP.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Network Card.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSetIP.setIcon(icon12)
        self.btnSetIP.setIconSize(QtCore.QSize(50, 50))
        self.btnSetIP.setObjectName(_fromUtf8("btnSetIP"))
        self.gridLayout.addWidget(self.btnSetIP, 0, 5, 1, 1)
        self.txtWallpaper = QtGui.QLineEdit(self.gridLayoutAnalyze)
        self.txtWallpaper.setObjectName(_fromUtf8("txtWallpaper"))
        self.gridLayout.addWidget(self.txtWallpaper, 1, 6, 1, 1)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/028.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabGeneral, icon13, _fromUtf8("General"))
        self.tabFFU = QtGui.QWidget()
        self.tabFFU.setObjectName(_fromUtf8("tabFFU"))
        self.comboBox = QtGui.QComboBox(self.tabFFU)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 120, 25))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.tabFFU)
        self.label_4.setGeometry(QtCore.QRect(260, 10, 391, 151))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btnFFU_Run = QtGui.QPushButton(self.tabFFU)
        self.btnFFU_Run.setGeometry(QtCore.QRect(10, 80, 120, 41))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Installing Updates.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btnFFU_Run.setIcon(icon14)
        self.btnFFU_Run.setIconSize(QtCore.QSize(32, 32))
        self.btnFFU_Run.setObjectName(_fromUtf8("btnFFU_Run"))
        self.txtFlufPath = QtGui.QLineEdit(self.tabFFU)
        self.txtFlufPath.setGeometry(QtCore.QRect(10, 50, 121, 20))
        self.txtFlufPath.setObjectName(_fromUtf8("txtFlufPath"))
        self.btnFindFlufFile = QtGui.QToolButton(self.tabFFU)
        self.btnFindFlufFile.setGeometry(QtCore.QRect(134, 50, 31, 21))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/Show Password.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFindFlufFile.setIcon(icon15)
        self.btnFindFlufFile.setObjectName(_fromUtf8("btnFindFlufFile"))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/016.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabFFU, icon16, _fromUtf8("FFU"))
        self.tabAnalyze = QtGui.QWidget()
        self.tabAnalyze.setObjectName(_fromUtf8("tabAnalyze"))
        self.gridLayoutAnalyze_2 = QtGui.QWidget(self.tabAnalyze)
        self.gridLayoutAnalyze_2.setGeometry(QtCore.QRect(12, 7, 651, 151))
        self.gridLayoutAnalyze_2.setObjectName(_fromUtf8("gridLayoutAnalyze_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutAnalyze_2)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnDisableWinUpdate_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnDisableWinUpdate_2.setText(_fromUtf8(""))
        self.btnDisableWinUpdate_2.setIcon(icon1)
        self.btnDisableWinUpdate_2.setIconSize(QtCore.QSize(50, 50))
        self.btnDisableWinUpdate_2.setObjectName(_fromUtf8("btnDisableWinUpdate_2"))
        self.gridLayout_2.addWidget(self.btnDisableWinUpdate_2, 1, 2, 1, 1)
        self.btnShowSysInfo_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnShowSysInfo_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnShowSysInfo_2.setText(_fromUtf8(""))
        self.btnShowSysInfo_2.setIcon(icon2)
        self.btnShowSysInfo_2.setIconSize(QtCore.QSize(50, 50))
        self.btnShowSysInfo_2.setObjectName(_fromUtf8("btnShowSysInfo_2"))
        self.gridLayout_2.addWidget(self.btnShowSysInfo_2, 1, 1, 1, 1)
        self.btnClearLogs_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnClearLogs_2.setText(_fromUtf8(""))
        self.btnClearLogs_2.setIcon(icon3)
        self.btnClearLogs_2.setIconSize(QtCore.QSize(50, 50))
        self.btnClearLogs_2.setObjectName(_fromUtf8("btnClearLogs_2"))
        self.gridLayout_2.addWidget(self.btnClearLogs_2, 1, 3, 1, 1)
        self.btnScheduller_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnScheduller_2.setText(_fromUtf8(""))
        self.btnScheduller_2.setIcon(icon4)
        self.btnScheduller_2.setIconSize(QtCore.QSize(50, 50))
        self.btnScheduller_2.setObjectName(_fromUtf8("btnScheduller_2"))
        self.gridLayout_2.addWidget(self.btnScheduller_2, 0, 2, 1, 1)
        self.btnUAC_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnUAC_2.setText(_fromUtf8(""))
        self.btnUAC_2.setIcon(icon5)
        self.btnUAC_2.setIconSize(QtCore.QSize(50, 50))
        self.btnUAC_2.setObjectName(_fromUtf8("btnUAC_2"))
        self.gridLayout_2.addWidget(self.btnUAC_2, 0, 1, 1, 1)
        self.btnNoRestartBSOD_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnNoRestartBSOD_2.setText(_fromUtf8(""))
        self.btnNoRestartBSOD_2.setIcon(icon6)
        self.btnNoRestartBSOD_2.setIconSize(QtCore.QSize(50, 50))
        self.btnNoRestartBSOD_2.setObjectName(_fromUtf8("btnNoRestartBSOD_2"))
        self.gridLayout_2.addWidget(self.btnNoRestartBSOD_2, 1, 0, 1, 1)
        self.btnPower_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnPower_2.setText(_fromUtf8(""))
        self.btnPower_2.setIcon(icon7)
        self.btnPower_2.setIconSize(QtCore.QSize(50, 50))
        self.btnPower_2.setObjectName(_fromUtf8("btnPower_2"))
        self.gridLayout_2.addWidget(self.btnPower_2, 0, 3, 1, 1)
        self.btnDisableFirewall_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnDisableFirewall_2.setText(_fromUtf8(""))
        self.btnDisableFirewall_2.setIcon(icon8)
        self.btnDisableFirewall_2.setIconSize(QtCore.QSize(50, 50))
        self.btnDisableFirewall_2.setObjectName(_fromUtf8("btnDisableFirewall_2"))
        self.gridLayout_2.addWidget(self.btnDisableFirewall_2, 0, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.gridLayoutAnalyze_2)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 6, 1, 1)
        self.btnWallpaper_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnWallpaper_2.setText(_fromUtf8(""))
        self.btnWallpaper_2.setIcon(icon9)
        self.btnWallpaper_2.setIconSize(QtCore.QSize(50, 50))
        self.btnWallpaper_2.setObjectName(_fromUtf8("btnWallpaper_2"))
        self.gridLayout_2.addWidget(self.btnWallpaper_2, 1, 5, 1, 1)
        self.btnTODO_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.btnTODO_2.setText(_fromUtf8(""))
        self.btnTODO_2.setIcon(icon10)
        self.btnTODO_2.setIconSize(QtCore.QSize(50, 50))
        self.btnTODO_2.setObjectName(_fromUtf8("btnTODO_2"))
        self.gridLayout_2.addWidget(self.btnTODO_2, 1, 4, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setIcon(icon11)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 4, 1, 1)
        self.btnSetIP_2 = QtGui.QPushButton(self.gridLayoutAnalyze_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetIP_2.sizePolicy().hasHeightForWidth())
        self.btnSetIP_2.setSizePolicy(sizePolicy)
        self.btnSetIP_2.setText(_fromUtf8(""))
        self.btnSetIP_2.setIcon(icon12)
        self.btnSetIP_2.setIconSize(QtCore.QSize(50, 50))
        self.btnSetIP_2.setObjectName(_fromUtf8("btnSetIP_2"))
        self.gridLayout_2.addWidget(self.btnSetIP_2, 0, 5, 1, 1)
        self.txtWallpaper_2 = QtGui.QLineEdit(self.gridLayoutAnalyze_2)
        self.txtWallpaper_2.setObjectName(_fromUtf8("txtWallpaper_2"))
        self.gridLayout_2.addWidget(self.txtWallpaper_2, 1, 6, 1, 1)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/126.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabAnalyze, icon17, _fromUtf8("Analyze"))
        self.tabDebugger = QtGui.QWidget()
        self.tabDebugger.setStyleSheet(_fromUtf8(""))
        self.tabDebugger.setObjectName(_fromUtf8("tabDebugger"))
        self.txtPort = QtGui.QLineEdit(self.tabDebugger)
        self.txtPort.setGeometry(QtCore.QRect(10, 10, 200, 20))
        self.txtPort.setObjectName(_fromUtf8("txtPort"))
        self.txtHost = QtGui.QLineEdit(self.tabDebugger)
        self.txtHost.setGeometry(QtCore.QRect(10, 40, 200, 20))
        self.txtHost.setObjectName(_fromUtf8("txtHost"))
        self.lblPort = QtGui.QLabel(self.tabDebugger)
        self.lblPort.setGeometry(QtCore.QRect(220, 13, 47, 13))
        self.lblPort.setObjectName(_fromUtf8("lblPort"))
        self.label = QtGui.QLabel(self.tabDebugger)
        self.label.setGeometry(QtCore.QRect(220, 43, 47, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_3 = QtGui.QPushButton(self.tabDebugger)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 130, 201, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_2 = QtGui.QLabel(self.tabDebugger)
        self.label_2.setGeometry(QtCore.QRect(270, -10, 391, 151))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.checkBox = QtGui.QCheckBox(self.tabDebugger)
        self.checkBox.setGeometry(QtCore.QRect(10, 100, 70, 17))
        self.checkBox.setStyleSheet(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabDebugger)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 70, 201, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_3 = QtGui.QLabel(self.tabDebugger)
        self.label_3.setGeometry(QtCore.QRect(222, 74, 47, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("./sources/192.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabDebugger, icon18, _fromUtf8("Debugger"))
        self.verticalLayout.addWidget(self.tabWidget)
        self.output = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.output.setObjectName(_fromUtf8("output"))
        self.verticalLayout.addWidget(self.output)
        self.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(self)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 711, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(self)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        self.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(self)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        self.setStatusBar(self.statusBar)
        self.actionRun_1 = QtGui.QAction(self)
        self.actionRun_1.setObjectName(_fromUtf8("actionRun_1"))
        self.actionRun_2 = QtGui.QAction(self)
        self.actionRun_2.setObjectName(_fromUtf8("actionRun_2"))
        self.action_Help = QtGui.QAction(self)
        self.action_Help.setObjectName(_fromUtf8("action_Help"))
        self.action_About = QtGui.QAction(self)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuRun.addAction(self.actionRun_1)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRun_2)
        self.menuHelp.addAction(self.action_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_About)
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        # QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        self.setWindowTitle(_translate("MainWindow", "EasyQA", None))
        self.btnDisableWinUpdate.setToolTip(_translate("MainWindow", "Disable update", None))
        self.btnDisableWinUpdate.setStatusTip(_translate("MainWindow", "Disable Windows update service", None))
        self.btnShowSysInfo.setToolTip(_translate("MainWindow",
                                                  "<html><head/><body><p><span style=\" font-weight:600;\">Show system info</span></p></body></html>",
                                                  None))
        self.btnShowSysInfo.setStatusTip(
            _translate("MainWindow", "Show system information (version, drivers, etc)", None))
        self.btnClearLogs.setToolTip(_translate("MainWindow", "Clear events", None))
        self.btnClearLogs.setStatusTip(_translate("MainWindow", "Clear Windows Event Log", None))
        self.btnScheduller.setToolTip(_translate("MainWindow", "Disable shceduller", None))
        self.btnScheduller.setStatusTip(_translate("MainWindow", "Disable windows sceduller", None))
        self.btnUAC.setToolTip(_translate("MainWindow", "Disable UAC", None))
        self.btnUAC.setStatusTip(_translate("MainWindow", "Disable User Account Control", None))
        self.btnNoRestartBSOD.setToolTip(_translate("MainWindow", "No restart on BSOD", None))
        self.btnNoRestartBSOD.setStatusTip(_translate("MainWindow", "Change option restart on BSOD to disable", None))
        self.btnPower.setToolTip(_translate("MainWindow",
                                            "<html><head/><body><p><span style=\" font-weight:600;\">Change power scheme</span></p></body></html>",
                                            None))
        self.btnPower.setStatusTip(
            _translate("MainWindow", "Change power scheme for test (no sleep, no hibarnate etc.)", None))
        self.btnDisableFirewall.setToolTip(_translate("MainWindow", "Disable firewall", None))
        self.btnDisableFirewall.setStatusTip(_translate("MainWindow", "Click button to disable Windows firewall", None))
        self.lineEdit.setText(_translate("MainWindow", "192.168.0.2", None))
        self.btnWallpaper.setToolTip(_translate("MainWindow", "Write text on wallpaper", None))
        self.btnWallpaper.setStatusTip(
            _translate("MainWindow", "Write text and click button to add this text on desktop", None))
        self.btnTODO.setToolTip(_translate("MainWindow", "TODO", None))
        self.btnTODO.setStatusTip(_translate("MainWindow", "TODO", None))
        self.pushButton.setToolTip(_translate("MainWindow", "Setup debugger", None))
        self.pushButton.setStatusTip(
            _translate("MainWindow", "Run to setup windows debugger (you should copy the key!)", None))
        self.btnSetIP.setToolTip(_translate("MainWindow", "Set IP", None))
        self.btnSetIP.setStatusTip(_translate("MainWindow", "Manual setup IP for this host ", None))
        self.txtWallpaper.setText(_translate("MainWindow", "Host 777", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("MainWindow", "General", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "P0016EGQ", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "P0014EGQ", None))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p><img src=\":/sources/sources/FAQ.png\"/><span style=\" font-weight:600;\">The FFU GUI Tool. </span></p><p><span style=\" font-weight:600;\">You have to choose FW version and press Run.<br/></span></p><p><span style=\" font-weight:600; font-style:italic; color:#ff0000;\">Warning! This is your responsibility to check if it possible <br/>to commit FFU upgrade from one version to another !</span></p></body></html>",
                                        None))
        self.btnFFU_Run.setText(_translate("MainWindow", "Run", None))
        self.btnFindFlufFile.setText(_translate("MainWindow", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFFU), _translate("MainWindow", "FFU", None))
        self.btnDisableWinUpdate_2.setToolTip(_translate("MainWindow", "Disable update", None))
        self.btnDisableWinUpdate_2.setStatusTip(_translate("MainWindow", "Disable Windows update service", None))
        self.btnShowSysInfo_2.setToolTip(_translate("MainWindow",
                                                    "<html><head/><body><p><span style=\" font-weight:600;\">Show system info</span></p></body></html>",
                                                    None))
        self.btnShowSysInfo_2.setStatusTip(
            _translate("MainWindow", "Show system information (version, drivers, etc)", None))
        self.btnClearLogs_2.setToolTip(_translate("MainWindow", "Clear events", None))
        self.btnClearLogs_2.setStatusTip(_translate("MainWindow", "Clear Windows Event Log", None))
        self.btnScheduller_2.setToolTip(_translate("MainWindow", "Disable shceduller", None))
        self.btnScheduller_2.setStatusTip(_translate("MainWindow", "Disable windows sceduller", None))
        self.btnUAC_2.setToolTip(_translate("MainWindow", "Disable UAC", None))
        self.btnUAC_2.setStatusTip(_translate("MainWindow", "Disable User Account Control", None))
        self.btnNoRestartBSOD_2.setToolTip(_translate("MainWindow", "No restart on BSOD", None))
        self.btnNoRestartBSOD_2.setStatusTip(_translate("MainWindow", "Change option restart on BSOD to disable", None))
        self.btnPower_2.setToolTip(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-weight:600;\">Change power scheme</span></p></body></html>",
                                              None))
        self.btnPower_2.setStatusTip(
            _translate("MainWindow", "Change power scheme for test (no sleep, no hibarnate etc.)", None))
        self.btnDisableFirewall_2.setToolTip(_translate("MainWindow", "Disable firewall", None))
        self.btnDisableFirewall_2.setStatusTip(
            _translate("MainWindow", "Click button to disable Windows firewall", None))
        self.lineEdit_3.setText(_translate("MainWindow", "192.168.0.2", None))
        self.btnWallpaper_2.setToolTip(_translate("MainWindow", "Write text on wallpaper", None))
        self.btnWallpaper_2.setStatusTip(
            _translate("MainWindow", "Write text and click button to add this text on desktop", None))
        self.btnTODO_2.setToolTip(_translate("MainWindow", "TODO", None))
        self.btnTODO_2.setStatusTip(_translate("MainWindow", "TODO", None))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Setup debugger", None))
        self.pushButton_2.setStatusTip(
            _translate("MainWindow", "Run to setup windows debugger (you should copy the key!)", None))
        self.btnSetIP_2.setToolTip(_translate("MainWindow", "Set IP", None))
        self.btnSetIP_2.setStatusTip(_translate("MainWindow", "Manual setup IP for this host ", None))
        self.txtWallpaper_2.setText(_translate("MainWindow", "Host 777", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalyze), _translate("MainWindow", "Analyze", None))
        self.txtPort.setText(_translate("MainWindow", "50000", None))
        self.txtHost.setText(_translate("MainWindow", "192.168.0.1", None))
        self.lblPort.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">Port</span></p></body></html>",
                                        None))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-weight:600;\">Host</span></p></body></html>",
                                      None))
        self.pushButton_3.setText(_translate("MainWindow", "Setup debuging", None))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p><img src=\":/sources/sources/FAQ.png\"/><span style=\" font-weight:600;\">This client part of debugging setup.</span></p><p><span style=\" font-weight:600;\">You should generate key and provide this key to WinDbg. <br/>The Host is IP address of host running WinDbg</span></p><p><span style=\" font-weight:600;\">The Port is port to connect. The Port have to be uniq for every client.<br/></span></p></body></html>",
                                        None))
        self.checkBox.setText(_translate("MainWindow", "DHCP Off", None))
        self.lineEdit_2.setText(_translate("MainWindow", "PlatformName123", None))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">Key</span></p></body></html>",
                                        None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDebugger), _translate("MainWindow", "Debugger", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionRun_1.setText(_translate("MainWindow", "Run 1", None))
        self.actionRun_2.setText(_translate("MainWindow", "Run 2", None))
        self.action_Help.setText(_translate("MainWindow", "&Help", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))


# import resource_rc

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    w = Ui_MainWindow()

    w.show()
    sys.exit(app.exec_())
