# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\33398\PycharmProjects\FQA\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(711, 452)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Box Sync/gt/EasyQA/icons/064.png")), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 691, 391))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayoutMain = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutMain.setMargin(11)
        self.verticalLayoutMain.setSpacing(6)
        self.verticalLayoutMain.setObjectName(_fromUtf8("verticalLayoutMain"))
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setStyleSheet(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.gridLayoutWidget = QtGui.QWidget(self.tabGeneral)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 521, 151))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayoutGeneral = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutGeneral.setMargin(11)
        self.gridLayoutGeneral.setSpacing(6)
        self.gridLayoutGeneral.setObjectName(_fromUtf8("gridLayoutGeneral"))
        self.btnScheduller = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnScheduller.setText(_fromUtf8(""))
        self.btnScheduller.clicked.connect(self.btnScheduuler_Clicked)

        # QtCore.QObject.connect(self.btnScheduller, QtCore.SIGNAL("clicked()"), self.btnScheduuler_Clicked)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Administrative Tools.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnScheduller.setIcon(icon1)
        self.btnScheduller.setIconSize(QtCore.QSize(50, 50))
        self.btnScheduller.setObjectName(_fromUtf8("btnScheduller"))
        self.gridLayoutGeneral.addWidget(self.btnScheduller, 0, 2, 1, 1)
        self.btnUAC = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnUAC.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Remove User Male.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnUAC.setIcon(icon2)
        self.btnUAC.setIconSize(QtCore.QSize(50, 50))
        self.btnUAC.setObjectName(_fromUtf8("btnUAC"))
        self.gridLayoutGeneral.addWidget(self.btnUAC, 0, 1, 1, 1)
        self.btnDisableFirewall = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnDisableFirewall.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Firewall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDisableFirewall.setIcon(icon3)
        self.btnDisableFirewall.setIconSize(QtCore.QSize(50, 50))
        self.btnDisableFirewall.setObjectName(_fromUtf8("btnDisableFirewall"))
        self.gridLayoutGeneral.addWidget(self.btnDisableFirewall, 0, 0, 1, 1)
        self.txtIP = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txtIP.setObjectName(_fromUtf8("txtIP"))
        self.gridLayoutGeneral.addWidget(self.txtIP, 0, 7, 1, 1)
        self.txtWallpaper = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txtWallpaper.setObjectName(_fromUtf8("txtWallpaper"))
        self.gridLayoutGeneral.addWidget(self.txtWallpaper, 1, 7, 1, 1)
        self.btnPower = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnPower.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/120.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPower.setIcon(icon4)
        self.btnPower.setIconSize(QtCore.QSize(50, 50))
        self.btnPower.setObjectName(_fromUtf8("btnPower"))
        self.gridLayoutGeneral.addWidget(self.btnPower, 1, 0, 1, 1)
        self.btnDisableWinUpdate = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnDisableWinUpdate.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Disclaimer.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnDisableWinUpdate.setIcon(icon5)
        self.btnDisableWinUpdate.setIconSize(QtCore.QSize(50, 50))
        self.btnDisableWinUpdate.setObjectName(_fromUtf8("btnDisableWinUpdate"))
        self.gridLayoutGeneral.addWidget(self.btnDisableWinUpdate, 0, 4, 1, 1)
        self.btnShowSysInfo = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnShowSysInfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnShowSysInfo.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/System Task.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnShowSysInfo.setIcon(icon6)
        self.btnShowSysInfo.setIconSize(QtCore.QSize(50, 50))
        self.btnShowSysInfo.setObjectName(_fromUtf8("btnShowSysInfo"))
        self.gridLayoutGeneral.addWidget(self.btnShowSysInfo, 1, 2, 1, 1)
        self.btnNoRestartBSOD = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnNoRestartBSOD.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Support_2.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnNoRestartBSOD.setIcon(icon7)
        self.btnNoRestartBSOD.setIconSize(QtCore.QSize(50, 50))
        self.btnNoRestartBSOD.setObjectName(_fromUtf8("btnNoRestartBSOD"))
        self.gridLayoutGeneral.addWidget(self.btnNoRestartBSOD, 0, 3, 1, 1)
        self.btnClearLogs = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnClearLogs.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Urgent Property.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnClearLogs.setIcon(icon8)
        self.btnClearLogs.setIconSize(QtCore.QSize(50, 50))
        self.btnClearLogs.setObjectName(_fromUtf8("btnClearLogs"))
        self.gridLayoutGeneral.addWidget(self.btnClearLogs, 1, 1, 1, 1)
        self.btnTODO = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnTODO.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Edit Property.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btnTODO.setIcon(icon9)
        self.btnTODO.setIconSize(QtCore.QSize(50, 50))
        self.btnTODO.setObjectName(_fromUtf8("btnTODO"))
        self.gridLayoutGeneral.addWidget(self.btnTODO, 1, 3, 1, 1)
        self.btnWallpaper = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnWallpaper.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Virtual Machine 2.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btnWallpaper.setIcon(icon10)
        self.btnWallpaper.setIconSize(QtCore.QSize(50, 50))
        self.btnWallpaper.setObjectName(_fromUtf8("btnWallpaper"))
        self.gridLayoutGeneral.addWidget(self.btnWallpaper, 1, 4, 1, 1)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../Box Sync/gt/EasyQA/icons/028.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabGeneral, icon11, _fromUtf8(""))
        self.tabFFU = QtGui.QWidget()
        self.tabFFU.setObjectName(_fromUtf8("tabFFU"))
        self.comboBoxFFU = QtGui.QComboBox(self.tabFFU)
        self.comboBoxFFU.setGeometry(QtCore.QRect(10, 10, 90, 25))
        self.comboBoxFFU.setObjectName(_fromUtf8("comboBoxFFU"))
        self.comboBoxFFU.addItem(_fromUtf8(""))
        self.comboBoxFFU.addItem(_fromUtf8(""))
        self.lblFFU_Info = QtGui.QLabel(self.tabFFU)
        self.lblFFU_Info.setGeometry(QtCore.QRect(300, 10, 351, 151))
        self.lblFFU_Info.setObjectName(_fromUtf8("lblFFU_Info"))
        self.btnFFU_Run = QtGui.QPushButton(self.tabFFU)
        self.btnFFU_Run.setGeometry(QtCore.QRect(10, 80, 120, 41))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Installing Updates.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btnFFU_Run.setIcon(icon12)
        self.btnFFU_Run.setIconSize(QtCore.QSize(32, 32))
        self.btnFFU_Run.setObjectName(_fromUtf8("btnFFU_Run"))
        self.txtFlufPath = QtGui.QLineEdit(self.tabFFU)
        self.txtFlufPath.setGeometry(QtCore.QRect(110, 10, 121, 20))
        self.txtFlufPath.setObjectName(_fromUtf8("txtFlufPath"))
        self.btnFindFlufFile = QtGui.QToolButton(self.tabFFU)
        self.btnFindFlufFile.setGeometry(QtCore.QRect(230, 10, 35, 20))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/Show Password.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btnFindFlufFile.setIcon(icon13)
        self.btnFindFlufFile.setObjectName(_fromUtf8("btnFindFlufFile"))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("../../Box Sync/gt/EasyQA/icons/016.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabFFU, icon14, _fromUtf8(""))
        self.tabAnalyze = QtGui.QWidget()
        self.tabAnalyze.setObjectName(_fromUtf8("tabAnalyze"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tabAnalyze)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(12, 7, 651, 151))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayoutAnalyze = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutAnalyze.setMargin(11)
        self.gridLayoutAnalyze.setSpacing(6)
        self.gridLayoutAnalyze.setObjectName(_fromUtf8("gridLayoutAnalyze"))
        self.btnDisableWinUpdate_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnDisableWinUpdate_2.setText(_fromUtf8(""))
        self.btnDisableWinUpdate_2.setIcon(icon5)
        self.btnDisableWinUpdate_2.setIconSize(QtCore.QSize(50, 50))
        self.btnDisableWinUpdate_2.setObjectName(_fromUtf8("btnDisableWinUpdate_2"))
        self.gridLayoutAnalyze.addWidget(self.btnDisableWinUpdate_2, 4, 2, 1, 1)
        self.btnShowSysInfo_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnShowSysInfo_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnShowSysInfo_2.setText(_fromUtf8(""))
        self.btnShowSysInfo_2.setIcon(icon6)
        self.btnShowSysInfo_2.setIconSize(QtCore.QSize(50, 50))
        self.btnShowSysInfo_2.setObjectName(_fromUtf8("btnShowSysInfo_2"))
        self.gridLayoutAnalyze.addWidget(self.btnShowSysInfo_2, 4, 1, 1, 1)
        self.btnCheck = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnCheck.setText(_fromUtf8(""))
        self.btnCheck.setIcon(icon8)
        self.btnCheck.setIconSize(QtCore.QSize(50, 50))
        self.btnCheck.setObjectName(_fromUtf8("btnCheck"))
        self.gridLayoutAnalyze.addWidget(self.btnCheck, 4, 3, 1, 1)
        self.btnNoRestartBSOD_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnNoRestartBSOD_2.setText(_fromUtf8(""))
        self.btnNoRestartBSOD_2.setIcon(icon7)
        self.btnNoRestartBSOD_2.setIconSize(QtCore.QSize(50, 50))
        self.btnNoRestartBSOD_2.setObjectName(_fromUtf8("btnNoRestartBSOD_2"))
        self.gridLayoutAnalyze.addWidget(self.btnNoRestartBSOD_2, 4, 0, 1, 1)
        self.btnEventViever = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnEventViever.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/sources/sources/System Information.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.btnEventViever.setIcon(icon15)
        self.btnEventViever.setIconSize(QtCore.QSize(50, 50))
        self.btnEventViever.setObjectName(_fromUtf8("btnEventViever"))
        self.gridLayoutAnalyze.addWidget(self.btnEventViever, 0, 0, 1, 1)
        self.btnTODO_2 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnTODO_2.setText(_fromUtf8(""))
        self.btnTODO_2.setIcon(icon9)
        self.btnTODO_2.setIconSize(QtCore.QSize(50, 50))
        self.btnTODO_2.setObjectName(_fromUtf8("btnTODO_2"))
        self.gridLayoutAnalyze.addWidget(self.btnTODO_2, 4, 4, 1, 1)
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.gridLayoutAnalyze.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.gridLayoutWidget_2)
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.gridLayoutAnalyze.addWidget(self.dateTimeEdit_2, 0, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayoutAnalyze.addWidget(self.comboBox, 0, 3, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayoutAnalyze.addWidget(self.lineEdit, 0, 4, 1, 1)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("../../Box Sync/gt/EasyQA/icons/126.png")), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabAnalyze, icon16, _fromUtf8(""))
        self.tabDebugger = QtGui.QWidget()
        self.tabDebugger.setStyleSheet(_fromUtf8(""))
        self.tabDebugger.setObjectName(_fromUtf8("tabDebugger"))
        self.txtPort = QtGui.QLineEdit(self.tabDebugger)
        self.txtPort.setGeometry(QtCore.QRect(10, 7, 200, 20))
        self.txtPort.setObjectName(_fromUtf8("txtPort"))
        self.txtHost = QtGui.QLineEdit(self.tabDebugger)
        self.txtHost.setGeometry(QtCore.QRect(10, 33, 200, 20))
        self.txtHost.setObjectName(_fromUtf8("txtHost"))
        self.lblPort = QtGui.QLabel(self.tabDebugger)
        self.lblPort.setGeometry(QtCore.QRect(220, 10, 47, 13))
        self.lblPort.setObjectName(_fromUtf8("lblPort"))
        self.label = QtGui.QLabel(self.tabDebugger)
        self.label.setGeometry(QtCore.QRect(220, 36, 47, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_3 = QtGui.QPushButton(self.tabDebugger)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 130, 201, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_2 = QtGui.QLabel(self.tabDebugger)
        self.label_2.setGeometry(QtCore.QRect(270, -10, 391, 151))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.checkBox = QtGui.QCheckBox(self.tabDebugger)
        self.checkBox.setGeometry(QtCore.QRect(10, 109, 70, 17))
        self.checkBox.setStyleSheet(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabDebugger)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 87, 201, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_3 = QtGui.QLabel(self.tabDebugger)
        self.label_3.setGeometry(QtCore.QRect(220, 89, 47, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tabDebugger)
        self.label_4.setGeometry(QtCore.QRect(220, 64, 47, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.txtHost_2 = QtGui.QLineEdit(self.tabDebugger)
        self.txtHost_2.setGeometry(QtCore.QRect(10, 60, 200, 20))
        self.txtHost_2.setObjectName(_fromUtf8("txtHost_2"))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/192.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabDebugger, icon17, _fromUtf8(""))
        self.verticalLayoutMain.addWidget(self.tabWidget)
        self.output = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.output.setObjectName(_fromUtf8("output"))
        self.verticalLayoutMain.addWidget(self.output)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 711, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionRun_1 = QtGui.QAction(MainWindow)
        self.actionRun_1.setObjectName(_fromUtf8("actionRun_1"))
        self.actionRun_2 = QtGui.QAction(MainWindow)
        self.actionRun_2.setObjectName(_fromUtf8("actionRun_2"))
        self.action_Help = QtGui.QAction(MainWindow)
        self.action_Help.setObjectName(_fromUtf8("action_Help"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuRun.addAction(self.actionRun_1)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRun_2)
        self.menuHelp.addAction(self.action_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_About)
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyQA", None))
        self.btnScheduller.setToolTip(_translate("MainWindow", "Disable shceduller", None))
        self.btnScheduller.setStatusTip(_translate("MainWindow", "Disable windows sceduller", None))
        self.btnUAC.setToolTip(_translate("MainWindow", "Disable UAC", None))
        self.btnUAC.setStatusTip(_translate("MainWindow", "Disable User Account Control", None))
        self.btnDisableFirewall.setToolTip(_translate("MainWindow", "Disable firewall", None))
        self.btnDisableFirewall.setStatusTip(_translate("MainWindow", "Click button to disable Windows firewall", None))
        self.txtIP.setText(_translate("MainWindow", "192.168.0.2", None))
        self.txtWallpaper.setText(_translate("MainWindow", "Host 777", None))
        self.btnPower.setToolTip(_translate("MainWindow",
                                            "<html><head/><body><p><span style=\" font-weight:600;\">Change power scheme</span></p></body></html>",
                                            None))
        self.btnPower.setStatusTip(
            _translate("MainWindow", "Change power scheme for test (no sleep, no hibarnate etc.)", None))
        self.btnDisableWinUpdate.setToolTip(_translate("MainWindow", "Disable update", None))
        self.btnDisableWinUpdate.setStatusTip(_translate("MainWindow", "Disable Windows update service", None))
        self.btnShowSysInfo.setToolTip(_translate("MainWindow",
                                                  "<html><head/><body><p><span style=\" font-weight:600;\">Show system info</span></p></body></html>",
                                                  None))
        self.btnShowSysInfo.setStatusTip(
            _translate("MainWindow", "Show system information (version, drivers, etc)", None))
        self.btnNoRestartBSOD.setToolTip(_translate("MainWindow", "No restart on BSOD", None))
        self.btnNoRestartBSOD.setStatusTip(_translate("MainWindow", "Change option restart on BSOD to disable", None))
        self.btnClearLogs.setToolTip(_translate("MainWindow", "Clear events", None))
        self.btnClearLogs.setStatusTip(_translate("MainWindow", "Clear Windows Event Log", None))
        self.btnTODO.setToolTip(_translate("MainWindow", "TODO", None))
        self.btnTODO.setStatusTip(_translate("MainWindow", "TODO", None))
        self.btnWallpaper.setToolTip(_translate("MainWindow", "Write text on wallpaper", None))
        self.btnWallpaper.setStatusTip(
            _translate("MainWindow", "Write text and click button to add this text on desktop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("MainWindow", "General", None))
        self.comboBoxFFU.setItemText(0, _translate("MainWindow", "P0016EGQ", None))
        self.comboBoxFFU.setItemText(1, _translate("MainWindow", "P0014EGQ", None))
        self.lblFFU_Info.setText(_translate("MainWindow",
                                            "<html><head/><body><p><img src=\":/sources/sources/FAQ.png\"/><span style=\" font-weight:600;\">The FFU GUI Tool. </span></p><p><span style=\" font-weight:600;\">You have to choose FW version and press Run.<br/></span></p><p><span style=\" font-weight:600; font-style:italic; color:#ff0000;\">Warning! This is your responsibility to check if it possible <br/>to commit FFU upgrade from one version to another !</span></p></body></html>",
                                            None))
        self.btnFFU_Run.setText(_translate("MainWindow", "Run", None))
        self.txtFlufPath.setText(_translate("MainWindow", "to choose FLUF click ->", None))
        self.btnFindFlufFile.setText(_translate("MainWindow", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFFU), _translate("MainWindow", "FFU", None))
        self.btnDisableWinUpdate_2.setToolTip(_translate("MainWindow", "Disable update", None))
        self.btnDisableWinUpdate_2.setStatusTip(_translate("MainWindow", "Disable Windows update service", None))
        self.btnShowSysInfo_2.setToolTip(_translate("MainWindow",
                                                    "<html><head/><body><p><span style=\" font-weight:600;\">Show system info</span></p></body></html>",
                                                    None))
        self.btnShowSysInfo_2.setStatusTip(
            _translate("MainWindow", "Show system information (version, drivers, etc)", None))
        self.btnCheck.setToolTip(_translate("MainWindow", "Clear events", None))
        self.btnCheck.setStatusTip(_translate("MainWindow", "Clear Windows Event Log", None))
        self.btnNoRestartBSOD_2.setToolTip(_translate("MainWindow", "No restart on BSOD", None))
        self.btnNoRestartBSOD_2.setStatusTip(_translate("MainWindow", "Change option restart on BSOD to disable", None))
        self.btnEventViever.setToolTip(_translate("MainWindow", "Disable firewall", None))
        self.btnEventViever.setStatusTip(_translate("MainWindow", "Click button to disable Windows firewall", None))
        self.btnTODO_2.setToolTip(_translate("MainWindow", "TODO", None))
        self.btnTODO_2.setStatusTip(_translate("MainWindow", "TODO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalyze), _translate("MainWindow", "Analyze", None))
        self.txtPort.setText(_translate("MainWindow", "50000", None))
        self.txtHost.setText(_translate("MainWindow", "192.168.0.1", None))
        self.lblPort.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">Port</span></p></body></html>",
                                        None))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-weight:600;\">Host</span></p></body></html>",
                                      None))
        self.pushButton_3.setText(_translate("MainWindow", "Setup debuging", None))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p><img src=\":/sources/sources/FAQ.png\"/><span style=\" font-weight:600;\">This client part of debugging setup.</span></p><p><span style=\" font-weight:600;\">You should generate key and provide this key to WinDbg. <br/>The Host is IP address of host running WinDbg</span></p><p><span style=\" font-weight:600;\">The Port is port to connect. The Port have to be uniq for every client.<br/></span></p></body></html>",
                                        None))
        self.checkBox.setText(_translate("MainWindow", "DHCP Off", None))
        self.lineEdit_2.setText(_translate("MainWindow", "PlatformName123", None))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">Key</span></p></body></html>",
                                        None))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-weight:600;\">Client</span></p></body></html>",
                                        None))
        self.txtHost_2.setText(_translate("MainWindow", "192.168.0.1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDebugger), _translate("MainWindow", "Debugger", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionRun_1.setText(_translate("MainWindow", "Run 1", None))
        self.actionRun_2.setText(_translate("MainWindow", "Run 2", None))
        self.action_Help.setText(_translate("MainWindow", "&Help", None))
        self.action_About.setText(_translate("MainWindow", "&About", None))

    def btnScheduuler_Clicked(self):
        print("Clicked!")


if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    w = QtGui.QMainWindow()
    Ui_MainWindow().setupUi(w)
    w.show()
    sys.exit(app.exec_())
# import resource_rc
